<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'User ID' => 'ユーザID',
    'Role' => '役割',
    'Role ID' => '役割ID',
    'Status' => '状態',
    'Name' => '名前',
    'Email' => 'Email',
    'Username' => 'ユーザ名',
    'Auth Key' => '承認キー',
    'Access Token' => 'アクセストークン',
    'Logged In Ip' => 'ログイン元IP',
    'Logged In At' => 'ログイン日時',
    'Created Ip' => '作成元IP',
    'Created At' => '作成日時',
    'Updated At' => '更新日時',
    'Banned At' => 'BAN日時',
    'Banned Reason' => 'BAN理由',
    'Username' => 'ユーザ名',
    'New password' => '新しいパスワード',
    'Current password' => '現在のパスワード',
    'Login' => 'ログイン',
    'Password' => 'パスワード',

    'Email not found' => 'Email アドレスが一致しません',
    'Email / Username' => 'Email / ユーザ名',
    'Email / Username not found' => 'Email・ユーザ名が一致しません',
    'Username not found' => 'ユーザ名が一致しません',

    '{attribute} can contain only letters, numbers, and "_"' => '{attribute}は英数字とアンダーバーのみ使用できます',
    'Passwords do not match' => 'パスワードが一致しません',
    'Email Confirmation' => 'メールアドレスの確認',
];
